services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\ContentBlocks\:
    resource: '../Classes/*'

  TYPO3\CMS\ContentBlocks\UserFunction\:
    resource: '../Classes/UserFunction/*'
    public: true

# @todo change to BeforeTcaOverridesEvent for v13
  TYPO3\CMS\ContentBlocks\Generator\TcaGenerator:
    public: true
#    tags:
#      - name: event.listener
#        identifier: 'content-blocks-tca'
#        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

  TYPO3\CMS\ContentBlocks\Generator\PageTypeGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-page-types'
        event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent

  TYPO3\CMS\ContentBlocks\Generator\IconGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-icons'
        event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent

  TYPO3\CMS\ContentBlocks\Generator\TypoScriptGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-typoscript'
        event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent

#  @todo Use BeforeLoadedPageTsConfigEvent in v13
  TYPO3\CMS\ContentBlocks\Generator\PageTsConfigGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-page-tsconfig'
        event: TYPO3\CMS\Core\TypoScript\IncludeTree\Event\ModifyLoadedPageTsConfigEvent

#  @todo Use BeforeLoadedUserTsConfigEvent in v13
  TYPO3\CMS\ContentBlocks\Generator\UserTsConfigGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-user-tsconfig'
        event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent

  TYPO3\CMS\ContentBlocks\Generator\SqlGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-sql'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  TYPO3\CMS\ContentBlocks\Backend\Layout\HideContentElementChildrenEventListener:
    tags:
      - name: event.listener
        identifier: 'content-blocks-hide-children'
        event: TYPO3\CMS\Backend\View\Event\ModifyDatabaseQueryForContentEvent

  TYPO3\CMS\ContentBlocks\Backend\Preview\PreviewRenderer:
    public: true

  TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlocksDataProcessor:
    autoconfigure: false
    public: true
    tags:
      - { name: 'data.processor', identifier: 'content-blocks' }

  TYPO3\CMS\ContentBlocks\Basics\BasicsLoader:
    arguments:
      $cache: '@cache.core'

  TYPO3\CMS\ContentBlocks\Basics\BasicsRegistry:
    factory:
      - '@TYPO3\CMS\ContentBlocks\Basics\BasicsLoader'
      - 'load'

  TYPO3\CMS\ContentBlocks\Loader\ContentBlockLoader:
    arguments:
      $cache: '@cache.core'

  TYPO3\CMS\ContentBlocks\Definition\TableDefinitionCollection:
    factory:
      - '@TYPO3\CMS\ContentBlocks\Definition\Factory\TableDefinitionCollectionFactory'
      - 'create'

  TYPO3\CMS\ContentBlocks\Registry\ContentBlockRegistry:
    public: true
    factory:
      - '@TYPO3\CMS\ContentBlocks\Loader\ContentBlockLoader'
      - 'load'

  TYPO3\CMS\ContentBlocks\Registry\AutomaticLanguageKeysRegistry:
    factory:
      - '@TYPO3\CMS\ContentBlocks\Definition\TableDefinitionCollection'
      - 'getAutomaticLanguageKeysRegistry'

  TYPO3\CMS\ContentBlocks\Registry\LanguageFileRegistry:
    factory:
      - '@TYPO3\CMS\ContentBlocks\Registry\LanguageFileRegistryFactory'
      - 'create'

  TYPO3\CMS\ContentBlocks\Command\CreateContentBlockCommand:
    tags:
      - name: 'console.command'
        command: 'content-blocks:create'
        description: 'Create a Content Block'
        schedulable: false
      - name: 'console.command'
        command: 'make:content-block'

  TYPO3\CMS\ContentBlocks\Command\ListContentBlocksCommand:
    tags:
      - name: 'console.command'
        command: 'content-blocks:list'
        description: 'List available Content Blocks'
        schedulable: false

  TYPO3\CMS\ContentBlocks\Command\GenerateLanguageFileCommand:
    tags:
      - name: 'console.command'
        command: 'content-blocks:language:generate'
        description: 'Update Labels.xlf for the given Content Block'
        schedulable: false
